version: 2
before:
  hooks:
    - go mod tidy
    - go test ./...
builds:
  - id: windows
    env:
      - CGO_ENABLED=0
    goos:
      - windows
    flags:
      - -trimpath
    ldflags:
      - -s -w -X github.com/d-led/pathdebug/common.Version={{.Version}}
    hooks:
      pre:
        - go install mvdan.cc/garble@latest
        - garble -tiny -literals -seed=random build
  - id: non-windows
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
    ldflags:
      - -s -w -X github.com/d-led/pathdebug/common.Version={{.Version}}

archives:
  - formats: [ 'tar.gz' ]
    # this name template makes the OS and Arch compatible with the results of uname.
    name_template: >-
      {{ .ProjectName }}_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
      {{- if .Arm }}v{{ .Arm }}{{ end }}
    # use zip for windows archives
    format_overrides:
    - goos: windows
      formats: [ 'zip' ]
checksum:
  name_template: 'checksums.txt'
snapshot:
  version_template: "{{ incpatch .Version }}-next"
changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'

universal_binaries:
  - replace: true

brews:
  -
    name: pathdebug
    homepage: "https://github.com/d-led/pathdebug"
    repository:
      owner: d-led
      name: homebrew-d-led
    commit_author:
      name: Dmitry Ledentsov
      email: dmlled@yahoo.com

chocolateys:
  -
    name: pathdebug
    owners: Dmitry Ledentsov
    authors: Dmitry Ledentsov
    project_url: https://github.com/d-led/pathdebug
    project_source_url: https://github.com/d-led/pathdebug
    docs_url: https://github.com/d-led/pathdebug
    url_template: "https://github.com/d-led/pathdebug/releases/download/{{ .Tag }}/{{ .ArtifactName }}"
    copyright: 2023 Dmitry Ledentsov
    license_url: https://github.com/d-led/pathdebug/blob/main/LICENSE
    bug_tracker_url: https://github.com/d-led/pathdebug/issues
    tags: "environment variable path debug"
    summary: A simple interactive & one-shot tool to debug path list environment variables.
    description: |
      {{ .ProjectName }} installer package.
      A simple interactive & one-shot tool to debug path list environment variables.
      USAGE: `pathdebug PATH` or `pathdebug --h` for more options
    release_notes: "https://github.com/d-led/pathdebug/releases/tag/v{{ .Version }}"

    api_key: '{{ .Env.CHOCOLATEY_API_KEY }}'
    source_repo: "https://push.chocolatey.org/"
    skip_publish: false
    goamd64: v1


# The lines beneath this are called `modelines`. See `:help modeline`
# Feel free to remove those if you don't want/use them.
# yaml-language-server: $schema=https://goreleaser.com/static/schema.json
# vim: set ts=2 sw=2 tw=0 fo=cnqoj
